import { MetroStation } from '../types';

/**
 * Verified Official Station Alignment of Pune Metro (Maha Metro)
 * Includes Line 1 (Purple Line: PCMC to Swargate)
 * and Line 2 (Aqua Line: Vanaz to Ramwadi)
 * with Civil Court (District Court) Multilevel Interchange.
 */

export const PUNE_METRO_STATIONS: MetroStation[] = [
  // ==========================================
  // PURPLE LINE (Line 1: North to South Corridor)
  // ==========================================
  {
    id: 'pur-1',
    name: 'PCMC Bhavan',
    marathiName: 'पिंपरी-चिंचवड महानगरपालिका भवन',
    line: 'purple',
    lat: 18.6288,
    lng: 73.8052,
    order: 1,
  },
  {
    id: 'pur-2',
    name: 'Sant Tukaram Nagar',
    marathiName: 'संत तुकाराम नगर',
    line: 'purple',
    lat: 18.6200,
    lng: 73.8155,
    order: 2,
  },
  {
    id: 'pur-3',
    name: 'Bhosari (Nashik Phata)',
    marathiName: 'भोसरी (नाशिक फाटा)',
    line: 'purple',
    lat: 18.6074,
    lng: 73.8241,
    order: 3,
  },
  {
    id: 'pur-4',
    name: 'Kasarwadi',
    marathiName: 'कासारवाडी',
    line: 'purple',
    lat: 18.5975,
    lng: 73.8290,
    order: 4,
  },
  {
    id: 'pur-5',
    name: 'Phugewadi',
    marathiName: 'फुगेवाडी',
    line: 'purple',
    lat: 18.5866,
    lng: 73.8340,
    order: 5,
  },
  {
    id: 'pur-6',
    name: 'Dapodi',
    marathiName: 'दापोडी',
    line: 'purple',
    lat: 18.5775,
    lng: 73.8385,
    order: 6,
  },
  {
    id: 'pur-7',
    name: 'Bopodi',
    marathiName: 'बोपोडी',
    line: 'purple',
    lat: 18.5668,
    lng: 73.8427,
    order: 7,
  },
  {
    id: 'pur-8',
    name: 'Khadki',
    marathiName: 'खडकी',
    line: 'purple',
    lat: 18.5570,
    lng: 73.8480,
    order: 8,
  },
  {
    id: 'pur-9',
    name: 'Range Hills',
    marathiName: 'रेंज हिल्स',
    line: 'purple',
    lat: 18.5472,
    lng: 73.8520,
    order: 9,
  },
  {
    id: 'pur-10',
    name: 'Shivajinagar Metro',
    marathiName: 'शिवाजीनगर',
    line: 'purple',
    lat: 18.5314,
    lng: 73.8524,
    order: 10,
  },
  {
    id: 'pur-11',
    name: 'District Court (Civil Court)',
    marathiName: 'जिल्हा न्यायालय (सिव्हिल कोर्ट)',
    line: 'purple',
    lat: 18.5284,
    lng: 73.8576,
    order: 11,
    isInterchange: true,
  },
  {
    id: 'pur-12',
    name: 'Kasba Peth (Budhwar Peth)',
    marathiName: 'कसबा पेठ',
    line: 'purple',
    lat: 18.5195,
    lng: 73.8582,
    order: 12,
  },
  {
    id: 'pur-13',
    name: 'Mandai',
    marathiName: 'मंडई',
    line: 'purple',
    lat: 18.5140,
    lng: 73.8575,
    order: 13,
  },
  {
    id: 'pur-14',
    name: 'Swargate Metro',
    marathiName: 'स्वारगेट',
    line: 'purple',
    lat: 18.5018,
    lng: 73.8588,
    order: 14,
  },

  // ==========================================
  // AQUA LINE (Line 2: West to East Corridor)
  // ==========================================
  {
    id: 'aqua-1',
    name: 'Vanaz',
    marathiName: 'वनाज',
    line: 'aqua',
    lat: 18.5074,
    lng: 73.8042,
    order: 1,
  },
  {
    id: 'aqua-2',
    name: 'Anand Nagar',
    marathiName: 'आनंद नगर',
    line: 'aqua',
    lat: 18.5085,
    lng: 73.8140,
    order: 2,
  },
  {
    id: 'aqua-3',
    name: 'Ideal Colony',
    marathiName: 'आयडियल कॉलनी',
    line: 'aqua',
    lat: 18.5100,
    lng: 73.8225,
    order: 3,
  },
  {
    id: 'aqua-4',
    name: 'Nal Stop',
    marathiName: 'नळ स्टॉप',
    line: 'aqua',
    lat: 18.5115,
    lng: 73.8305,
    order: 4,
  },
  {
    id: 'aqua-5',
    name: 'Garware College',
    marathiName: 'गरवारे कॉलेज',
    line: 'aqua',
    lat: 18.5142,
    lng: 73.8370,
    order: 5,
  },
  {
    id: 'aqua-6',
    name: 'Deccan Gymkhana',
    marathiName: 'डेक्कन जिमखाना',
    line: 'aqua',
    lat: 18.5175,
    lng: 73.8440,
    order: 6,
  },
  {
    id: 'aqua-7',
    name: 'Chhatrapati Sambhaji Udyan',
    marathiName: 'छत्रपती संभाजी उद्यान',
    line: 'aqua',
    lat: 18.5210,
    lng: 73.8485,
    order: 7,
  },
  {
    id: 'aqua-8',
    name: 'PMC (Pune Municipal Corp)',
    marathiName: 'पुणे महानगरपालिका',
    line: 'aqua',
    lat: 18.5245,
    lng: 73.8525,
    order: 8,
  },
  {
    id: 'aqua-9',
    name: 'District Court (Civil Court)',
    marathiName: 'जिल्हा न्यायालय (सिव्हिल कोर्ट)',
    line: 'aqua',
    lat: 18.5284,
    lng: 73.8576,
    order: 9,
    isInterchange: true,
  },
  {
    id: 'aqua-10',
    name: 'Mangalwar Peth',
    marathiName: 'मंगळवार पेठ',
    line: 'aqua',
    lat: 18.5265,
    lng: 73.8640,
    order: 10,
  },
  {
    id: 'aqua-11',
    name: 'Pune Railway Station Metro',
    marathiName: 'पुणे रेल्वे स्टेशन',
    line: 'aqua',
    lat: 18.5285,
    lng: 73.8735,
    order: 11,
  },
  {
    id: 'aqua-12',
    name: 'Ruby Hall Clinic',
    marathiName: 'रुबी हॉल क्लिनिक',
    line: 'aqua',
    lat: 18.5320,
    lng: 73.8810,
    order: 12,
  },
  {
    id: 'aqua-13',
    name: 'Bundgarden',
    marathiName: 'बंडगार्डन',
    line: 'aqua',
    lat: 18.5365,
    lng: 73.8890,
    order: 13,
  },
  {
    id: 'aqua-14',
    name: 'Kalyani Nagar',
    marathiName: 'कल्याणी नगर',
    line: 'aqua',
    lat: 18.5480,
    lng: 73.9025,
    order: 14,
  },
  {
    id: 'aqua-15',
    name: 'Ramwadi',
    marathiName: 'रामवाडी',
    line: 'aqua',
    lat: 18.5555,
    lng: 73.9140,
    order: 15,
  },
];
